export const WHITE = '#fff'
export const WHITE_ALPHA = alpha => `rgba(255, 255, 255, ${alpha})`
export const SHADOW = 'rgba(0, 0, 0, 0.07)'
export const SNOW = '#fafcff'
export const SNOW_ALPHA = 'rgba(244, 246, 249, 0.75)'
export const ALLBIRDS_GRAY = '#EAEAEA'
export const BLACK = '#000'
export const BLACK_ALPHA = alpha => `rgba(0, 0, 0, ${alpha})`
export const DARK_GRAY = '#4A4A4A'
export const MEDIUM_GRAY = '#737373'
export const LIGHT_GRAY = '#B2B2B2'
export const FOCUS_GRAY = '#F0F0F0'
export const HOVER_GRAY = '#F8F8F8'
export const BORDER = 'rgba(0, 0, 0, 0.1)'

export const BABY_BLUE = '#eff7ff'
export const LIGHTER_BLUE = '#d9eafc'
export const LIGHT_BLUE = '#84add5'
export const BLUE = '#2980B9'
export const DARK_BLUE = '#246793'

export const LIGHT_GREEN = '#e8f9ec'
export const GREEN = '#3eaa6d'
export const FOREST = '#3a7553'
export const RED = '#e25152'
export const LIGHT_YELLOW = '#fff5dd'
export const YELLOW = '#ffc520'
export const MUSTARD = '#efb717'
export const ORANGE = '#faa432'
export const PURPLE = '#834fa0'

export const LIGHT_RED = '#f7dcdc'
export const LIGHTER_RED = '#f7e6e6'

export const CLUBS_PURPLE = '#66C1FF'
export const CLUBS_GREY = '#414654'
export const CLUBS_GREY_LIGHT = '#636773'
export const CLUBS_RED = '#FF776D'
export const CLUBS_YELLOW = '#FFCF59'
export const CLUBS_BLUE = '#60B8F2'
export const CLUBS_DEEP_BLUE = '#5ab0e8'

export const FLYER_BLUE = '#4954f4'
export const FLYER_NAVY = '#1f2049'
export const FLYER_PINK = '#ef4c5f'
