version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost+2.pem:/etc/nginx/certs/localhost+2.pem
      - ./localhost+2-key.pem:/etc/nginx/certs/localhost+2-key.pem