export const WHITE = '#fff'
export const SHADOW = 'rgba(0, 0, 0, 0.07)'
export const SNOW = '#fafcff'
export const SNOW_ALPHA = 'rgba(244, 246, 249, 0.75)'
export const ALLBIRDS_GRAY = '#EAEAEA'
export const BLACK = '#000'
export const BLACK_ALPHA = alpha => `rgba(0, 0, 0, ${alpha})`
export const DARK_GRAY = '#4A4A4A'
export const MEDIUM_GRAY = '#737373'
export const LIGHT_GRAY = '#B2B2B2'
export const FOCUS_GRAY = '#F0F0F0'
export const HOVER_GRAY = '#F8F8F8'
export const BORDER = 'rgba(0, 0, 0, 0.1)'

export const BABY_BLUE = '#eff7ff'
export const LIGHTER_BLUE = '#d9eafc'
export const LIGHT_BLUE = '#84add5'
export const BLUE = '#2980B9'
export const DARK_BLUE = '#246793'

export const LIGHT_GREEN = '#e8f9ec'
export const GREEN = '#3eaa6d'
export const FOREST = '#3a7553'
export const RED = '#e25152'
export const LIGHT_YELLOW = '#fff5dd'
export const YELLOW = '#ffc520'
export const MUSTARD = '#efb717'
export const ORANGE = '#faa432'
export const PURPLE = '#834fa0'
