[tool.ruff]
exclude = [
    ".venv",
    "migrations",
]
lint.ignore = ["E203"]
line-length = 88
lint.select = [
    "E",
    "F",
    "Q",
    "W",
    "I",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.isort]
known-first-party = ["pennclubs", "clubs"]
lines-after-imports = 2