# Generated by Django 2.2.5 on 2019-10-25 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0003_auto_20191025_2102"),
        ("clubs", "0003_auto_20191025_2120"),
    ]

    operations = []
