# Generated by Django 2.2.6 on 2019-11-01 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import clubs.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("clubs", "0005_auto_20191025_2218"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=clubs.models.get_user_file_name
                    ),
                ),
            ],
        )
    ]
