# Generated by Django 3.0 on 2019-12-06 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("clubs", "0008_subscribe"), ("clubs", "0008_auto_20191111_1835")]

    operations = []
