# Generated by Django 3.0 on 2019-12-06 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0009_merge_20191206_2311"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Note", max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "creating_club_permission",
                    models.IntegerField(
                        choices=[
                            (0, "Creating Club Owner"),
                            (10, "Creating Club Officers"),
                            (20, "Creating Club Members"),
                        ],
                        default=20,
                    ),
                ),
                (
                    "outside_club_permission",
                    models.IntegerField(
                        choices=[
                            (-1, "None"),
                            (0, "Subject Club Owner"),
                            (10, "Subject Club Officers"),
                            (20, "Subject Club Members"),
                            (100, "Public"),
                        ],
                        default=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creating_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_by_club",
                        to="clubs.Club",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("note_tags", models.ManyToManyField(to="clubs.NoteTag")),
                (
                    "subject_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_of_club",
                        to="clubs.Club",
                    ),
                ),
            ],
        ),
    ]
