# Generated by Django 3.0.2 on 2020-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0013_auto_20200112_2104"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
