# Generated by Django 3.0.2 on 2020-01-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20200112_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Recruitment')], default=1),
        ),
    ]
