# Generated by Django 3.0.2 on 2020-01-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_club_youtube'),
        ('clubs', '0014_event_type'),
    ]

    operations = [
    ]
