# Generated by Django 3.0.2 on 2020-01-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0015_auto_20200119_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
