# Generated by Django 3.0.2 on 2020-02-07 22:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0017_joinrequest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JoinRequest",
            new_name="MembershipRequest",
        ),
    ]
