# Generated by Django 3.0.3 on 2020-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'permissions': [('approve_club', 'Can approve pending clubs'), ('see_pending_clubs', "View pending clubs that are not one's own")]},
        ),
    ]
