# Generated by Django 3.0.2 on 2020-02-28 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0018_auto_20200207_1737"),
        ("clubs", "0017_report"),
    ]

    operations = []
