# Generated by Django 3.0.3 on 2020-02-23 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0018_auto_20200219_0903"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club", name="approved_on", field=models.DateTimeField(null=True),
        ),
    ]
