# Generated by Django 3.0.3 on 2020-03-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0021_auto_20200307_1913"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="approved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
