# Generated by Django 3.1 on 2020-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0028_auto_20200814_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="approved_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
