# Generated by Django 3.1 on 2020-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0031_auto_20200818_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
