# Generated by Django 3.1 on 2020-08-22 13:43

from django.db import migrations, models
from django.utils import timezone


def set_sac_defaults(apps, schema_editor):
    Club = apps.get_model("clubs", "Club")
    Club.objects.filter(fair_on__isnull=True).update(fair_on=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0033_auto_20200822_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="fair_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_sac_defaults, lambda apps, schema_editor: None),
        migrations.AddField(
            model_name="historicalclub",
            name="fair_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
