# Generated by Django 3.1 on 2020-08-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0035_merge_20200822_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="email_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="email_public",
            field=models.BooleanField(default=True),
        ),
    ]
