# Generated by Django 3.1 on 2020-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0036_auto_20200825_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Recruitment"),
                    (2, "GBM"),
                    (3, "Speaker"),
                    (0, "Other"),
                    (4, "Activities Fair"),
                ],
                default=1,
            ),
        ),
    ]
