# Generated by Django 3.1 on 2020-08-28 20:23

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Badge = apps.get_model("clubs", "Badge")
    db_alias = schema_editor.connection.alias
    for badge in Badge.objects.using(db_alias).all():
        if badge.label.startswith("SAC Fair - "):
            badge.label = badge.label.split("-", 1)[1].strip()
            badge.purpose = "fair"
            badge.save(update_fields=["label", "purpose"])


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0037_auto_20200826_1006"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="purpose",
            field=models.CharField(default="org", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, lambda apps, schema_editor: None),
    ]
