# Generated by Django 3.1 on 2020-08-31 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0038_badge_purpose"),
        ("clubs", "0035_clubvisit"),
    ]

    operations = []
