# Generated by Django 3.1.1 on 2020-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0039_merge_20200830_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="share_bookmarks",
            field=models.BooleanField(default=False),
        ),
    ]
