# Generated by Django 3.1.1 on 2020-09-12 14:56

from django.db import migrations, models

import clubs.models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0040_profile_share_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="image_small",
            field=models.ImageField(
                blank=True, null=True, upload_to=clubs.models.get_club_small_file_name
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="image_small",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
