# Generated by Django 3.1.1 on 2020-09-12 16:13

from django.db import migrations, models

import clubs.models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0041_auto_20200912_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_small",
            field=models.ImageField(
                blank=True, null=True, upload_to=clubs.models.get_event_small_file_name
            ),
        ),
    ]
