# Generated by Django 3.1.1 on 2020-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0042_event_image_small"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
