# Generated by Django 3.1.2 on 2020-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0043_auto_20200913_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="public",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advisor",
            name="school",
            field=models.ManyToManyField(blank=True, to="clubs.School"),
        ),
    ]
