# Generated by Django 3.1.2 on 2020-10-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0043_auto_20200913_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="enables_subscription",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="enables_subscription",
            field=models.BooleanField(default=True),
        ),
    ]
