# Generated by Django 3.1.2 on 2020-10-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0044_auto_20201011_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="public",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advisor",
            name="school",
            field=models.ManyToManyField(blank=True, to="clubs.School"),
        ),
    ]
