# Generated by Django 3.1.2 on 2020-10-18 20:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0045_auto_20201011_2221"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="uuid_secret", field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
