# Generated by Django 3.1.2 on 2020-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_auto_20201011_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
