# Generated by Django 3.1.2 on 2020-10-18 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0046_profile_uuid_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
