# Generated by Django 3.1.2 on 2020-10-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0048_auto_20201018_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='student_types',
            field=models.ManyToManyField(blank=True, to='clubs.StudentType'),
        ),
    ]
