# Generated by Django 3.1.2 on 2020-10-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0048_auto_20201018_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
