# Generated by Django 3.1.2 on 2020-11-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0053_auto_20201031_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="recruiting_cycle",
            field=models.IntegerField(
                choices=[(1, "Unknown"), (2, "Fall"), (3, "Spring"), (4, "Both")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="recruiting_cycle",
            field=models.IntegerField(
                choices=[(1, "Unknown"), (2, "Fall"), (3, "Spring"), (4, "Both")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="application_required",
            field=models.IntegerField(
                choices=[
                    (1, "Open Membership"),
                    (3, "Audition Required"),
                    (2, "Tryout Required"),
                    (4, "Application Required"),
                    (5, "Application and Interview Required"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclub",
            name="application_required",
            field=models.IntegerField(
                choices=[
                    (1, "Open Membership"),
                    (3, "Audition Required"),
                    (2, "Tryout Required"),
                    (4, "Application Required"),
                    (5, "Application and Interview Required"),
                ],
                default=4,
            ),
        ),
    ]
