# Generated by Django 3.1.2 on 2020-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0054_auto_20201101_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="recruiting_cycle",
            field=models.IntegerField(
                choices=[
                    (1, "Unknown"),
                    (2, "Fall"),
                    (3, "Spring"),
                    (4, "Both"),
                    (5, "Open"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Other"),
                    (1, "Recruitment"),
                    (2, "GBM"),
                    (3, "Speaker"),
                    (4, "Activities Fair"),
                    (5, "Social"),
                    (6, "Career"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclub",
            name="recruiting_cycle",
            field=models.IntegerField(
                choices=[
                    (1, "Unknown"),
                    (2, "Fall"),
                    (3, "Spring"),
                    (4, "Both"),
                    (5, "Open"),
                ],
                default=1,
            ),
        ),
    ]
