# Generated by Django 3.1.2 on 2020-11-05 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0054_auto_20201101_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='recruiting_cycle',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Fall'), (3, 'Spring'), (4, 'Both'), (5, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='recruiting_cycle',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Fall'), (3, 'Spring'), (4, 'Both'), (5, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
