# Generated by Django 3.1.2 on 2020-11-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0054_auto_20201101_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='recruiting_cycle',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Fall'), (3, 'Spring'), (4, 'Both'), (5, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='recruiting_cycle',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Fall'), (3, 'Spring'), (4, 'Both'), (5, 'Open')], default=1),
        ),
    ]
