# Generated by Django 3.1.2 on 2020-11-18 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0055_auto_20201117_1457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisor",
            name="school",
        ),
        migrations.AddField(
            model_name="advisor",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="advisor",
            name="email",
            field=models.CharField(
                blank=True,
                max_length=320,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
