# Generated by Django 3.1.3 on 2020-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0058_badge_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_graduate",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ClubFair",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("organization", models.TextField()),
                ("contact", models.TextField()),
                ("time", models.TextField(blank=True)),
                ("information", models.TextField()),
                ("registration_information", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("registration_end_time", models.DateTimeField()),
                ("participating_clubs", models.ManyToManyField(blank=True, to="clubs.Club")),
            ],
        ),
    ]
