# Generated by Django 3.1.3 on 2020-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0058_badge_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="club", name="ics_import_url", field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="ics_import_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
