# Generated by Django 3.1.2 on 2020-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0058_badge_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[("recurring_event_id", models.AutoField(primary_key=True, serialize=False)),],
        ),
    ]
