# Generated by Django 3.1.3 on 2020-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0059_auto_20201207_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubfair",
            name="questions",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="clubfair",
            name="registration_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubfairregistration",
            name="answers",
            field=models.TextField(blank=True),
        ),
    ]
