# Generated by Django 3.1.3 on 2020-12-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0059_clubfair"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_graduate",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
