# Generated by Django 3.1.3 on 2020-12-10 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0060_auto_20201210_1251"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubfairregistration",
            name="registrant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
