# Generated by Django 3.1.4 on 2020-12-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0062_clubfairregistration_registrant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubfair",
            name="information",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clubfair",
            name="registration_information",
            field=models.TextField(blank=True),
        ),
    ]
