# Generated by Django 3.1.4 on 2020-12-16 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0063_auto_20201211_1311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("approve_club", "Can approve pending clubs"),
                    ("see_pending_clubs", "View pending clubs that are not one's own"),
                    (
                        "see_fair_status",
                        "See whether or not a club has registered for the SAC fair",
                    ),
                    ("manage_club", "Manipulate club object and related objects"),
                ],
            },
        ),
    ]
