# Generated by Django 3.1.2 on 2020-12-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0059_auto_20201205_1112"),
        ("clubs", "0065_auto_20201218_1830"),
    ]

    operations = []
