# Generated by Django 3.1.5 on 2021-01-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0068_clubapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="clubs.club",
            ),
        ),
    ]
