# Generated by Django 3.1.5 on 2021-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0070_clubvisit_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="purpose",
            field=models.CharField(
                choices=[("fair", "Fair"), ("org", "Organization")], max_length=255
            ),
        ),
    ]
