# Generated by Django 3.1.5 on 2021-01-15 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0070_clubvisit_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="fair",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clubs.clubfair",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="purpose",
            field=models.CharField(
                choices=[("fair", "Fair"), ("org", "Organization")], max_length=255
            ),
        ),
    ]
