# Generated by Django 3.1.5 on 2021-01-16 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0071_auto_20210115_1721"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomMeetingVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meeting_id", models.CharField(max_length=255)),
                ("participant_id", models.CharField(max_length=255)),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("leave_time", models.DateTimeField(null=True)),
                (
                    "club",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clubs.club"),
                ),
                ("event", models.ManyToManyField(null=True, to="clubs.Event")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
