# Generated by Django 3.1.6 on 2021-02-05 22:29

from django.db import migrations, models

import clubs.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0074_auto_20210120_1208"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="membership",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=clubs.models.get_membership_image_file_name,
            ),
        ),
    ]
