# Generated by Django 3.1.2 on 2021-02-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0076_auto_20210214_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='mission',
            field=models.TextField(blank=True),
        ),
    ]
