# Generated by Django 3.1.6 on 2021-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0077_auto_20210219_2014"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="affiliation",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Undergraduate"),
                    (1, "Masters"),
                    (2, "Professional"),
                    (3, "Doctoral"),
                    (4, "Staff"),
                ],
                default=0,
            ),
        ),
    ]
