# Generated by Django 3.1.2 on 2021-05-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0078_auto_20210502_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='student_types',
        ),
        migrations.CreateModel(
            name='TargetStudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('target_student_types', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.studenttype')),
            ],
        ),
    ]
