# Generated by Django 3.1.6 on 2021-05-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0078_auto_20210523_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="student_types",
            field=models.ManyToManyField(
                through="clubs.TargetStudentType", to="clubs.StudentType"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="target_majors",
            field=models.ManyToManyField(through="clubs.TargetMajor", to="clubs.Major"),
        ),
        migrations.AddField(
            model_name="club",
            name="target_schools",
            field=models.ManyToManyField(
                through="clubs.TargetSchool", to="clubs.School"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="target_years",
            field=models.ManyToManyField(through="clubs.TargetYear", to="clubs.Year"),
        ),
    ]
