# Generated by Django 3.1.2 on 2021-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0079_auto_20210517_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="student_types",
            field=models.ManyToManyField(
                through="clubs.TargetStudentType", to="clubs.StudentType"
            ),
        ),
    ]
