# Generated by Django 3.1.6 on 2021-07-18 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0079_auto_20210523_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'Free Response'), (2, 'Multiple Choice'), (3, 'Short Answer')], default=1)),
                ('prompt', models.TextField(blank=True)),
                ('precedence', models.IntegerField(default=0)),
                ('word_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.applicationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiple_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clubs.applicationmultiplechoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clubs.applicationquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='clubs.clubapplication'),
        ),
        migrations.AddField(
            model_name='applicationmultiplechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='clubs.applicationquestion'),
        ),
    ]
