# Generated by Django 3.2.6 on 2021-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0083_auto_20210901_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationquestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
