# Generated by Django 3.2.6 on 2021-10-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0086_adminnote"),
        ("clubs", "0086_applicationsubmission_archived"),
    ]

    operations = []
