# Generated by Django 3.2.6 on 2021-10-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0088_alter_applicationsubmission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsubmission",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Rejected after written application"),
                    (3, "Rejected after interview(s)"),
                    (4, "Accepted"),
                ],
                default=1,
            ),
        ),
    ]
