# Generated by Django 3.2.6 on 2021-10-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0087_merge_20211001_1738"),
        ("clubs", "0089_alter_applicationsubmission_status"),
    ]

    operations = []
