# Generated by Django 3.2.6 on 2021-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0090_adminnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
