# Generated by Django 3.2.18 on 2023-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0090_auto_20230106_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="favorite_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="club",
            name="membership_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="favorite_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="membership_count",
            field=models.IntegerField(default=0),
        ),
    ]
