# Generated by Django 3.2.16 on 2023-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0090_adminnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationsubmission",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicationsubmission",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clubapplication",
            name="acceptance_email",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clubapplication",
            name="rejection_email",
            field=models.TextField(blank=True),
        ),
    ]
