# Generated by Django 3.2.18 on 2024-01-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0091_applicationextension"),
        ("clubs", "0091_clubapplication_application_end_time_exception"),
    ]

    operations = []
