# Generated by Django 3.2.18 on 2024-01-06 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0092_merge_20240106_1117"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="applicationquestionresponse",
            unique_together={("question", "submission")},
        ),
        migrations.AlterUniqueTogether(
            name="applicationsubmission",
            unique_together={("user", "application", "committee")},
        ),
    ]
