# Generated by Django 3.2.18 on 2024-01-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0092_auto_20221118_1424"),
        ("clubs", "0094_applicationcycle_release_date"),
    ]

    operations = []
