# Generated by Django 3.2.18 on 2024-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0094_applicationcycle_release_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicationsubmission", name="archived",),
        migrations.AddField(
            model_name="club",
            name="favorite_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="club",
            name="membership_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="favorite_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="membership_count",
            field=models.IntegerField(default=0),
        ),
    ]
