# Generated by Django 3.2.18 on 2024-02-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0094_applicationcycle_release_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicationsubmission", name="archived",),
    ]
