# Generated by Django 3.2.18 on 2024-01-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0091_auto_20231019_1730"),
        ("clubs", "0094_applicationcycle_release_date"),
    ]

    operations = []
