# Generated by Django 3.2.18 on 2024-02-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0095_auto_20240202_2013"),
        ("clubs", "0095_remove_applicationsubmission_archived"),
    ]

    operations = []
