# Generated by Django 5.0.3 on 2024-03-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0095_merge_20240128_1321"),
        ("clubs", "0095_rm_field_add_count"),
    ]

    operations = [
    ]
