# Generated by Django 5.0.2 on 2024-03-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0095_rm_field_add_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipinvite",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
