# Generated by Django 5.0.3 on 2024-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0096_merge_20240304_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
