# Generated by Django 5.0.3 on 2024-04-13 22:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0097_ticket_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTransactionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reconciliation_id", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "buyer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("buyer_first_name", models.CharField(max_length=100)),
                ("buyer_last_name", models.CharField(max_length=100)),
                (
                    "buyer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="transaction_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="clubs.tickettransactionrecord",
            ),
        ),
    ]
