# Generated by Django 3.2.18 on 2024-04-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0096_membershipinvite_expires_at"),
        ("clubs", "0097_club_elo_historicalclub_elo_profile_time_since_vote"),
    ]

    operations = [
    ]
