# Generated by Django 5.0.3 on 2024-04-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0098_membershipinvite_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="elo",
        ),
        migrations.RemoveField(
            model_name="historicalclub",
            name="elo",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="time_since_vote",
        ),
    ]
