# Generated by Django 5.0.4 on 2024-04-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0096_merge_20240304_1450"),
        ("clubs", "0099_remove_club_elo_remove_historicalclub_elo_and_more"),
    ]

    operations = []
