# Generated by Django 5.0.3 on 2024-04-14 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0098_tickettransactionrecord_ticket_transaction_record"),
        ("clubs", "0100_merge_20240412_2206"),
    ]

    operations = []
