# Generated by Django 5.0.4 on 2024-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0101_merge_20240414_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticket_order_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
