# Generated by Django 5.0.4 on 2024-04-16 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0102_event_ticket_order_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="group_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="group_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
