# Generated by Django 5.0.4 on 2024-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0102_event_ticket_order_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticket_order_limit",
            field=models.IntegerField(default=10),
        ),
    ]
