# Generated by Django 5.0.4 on 2024-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0102_event_ticket_order_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="group_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="group_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
