# Generated by Django 5.0.4 on 2024-04-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0103_ticket_group_discount_ticket_group_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="checkout_context",
            field=models.CharField(blank=True, max_length=8297, null=True),
        ),
    ]
