# Generated by Django 5.0.4 on 2024-04-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0104_cart_checkout_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attended",
            field=models.BooleanField(default=False),
        ),
    ]
