# Generated by Django 5.0.4 on 2024-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0106_remove_ticket_transaction_record_ticket_transferable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attended",
            field=models.BooleanField(default=False),
        ),
    ]
