# Generated by Django 5.0.4 on 2024-04-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0108_ticket_buyable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettransactionrecord",
            name="ticket",
        ),
        migrations.AddField(
            model_name="ticket",
            name="transaction_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="clubs.tickettransactionrecord",
            ),
        ),
    ]
