# Generated by Django 5.0.4 on 2024-04-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0109_remove_tickettransactionrecord_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="holding_expiration",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
