# Generated by Django 5.0.4 on 2024-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0110_alter_ticket_holding_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="rank",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="historicalclub",
            name="rank",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
