# Generated by Django 5.0.4 on 2024-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0111_alter_club_rank_alter_historicalclub_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubfair",
            name="virtual",
            field=models.BooleanField(default=False),
        ),
    ]
