# Generated by Django 5.0.4 on 2024-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0114_alter_advisor_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="beta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="beta",
            field=models.BooleanField(default=False),
        ),
    ]
