# Generated by Django 5.0.4 on 2024-10-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0115_club_beta_historicalclub_beta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="approved_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalclub",
            name="approved_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
