# Generated by Django 5.0.4 on 2024-10-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0114_ownershiprequest"),
        ("clubs", "0116_alter_club_approved_on_and_more"),
    ]

    operations = [
    ]
