# Generated by Django 5.0.4 on 2025-01-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0117_clubapprovalresponsetemplate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="applicationcommittee", unique_together={("name", "application")},
        ),
    ]
