# Generated by Django 5.0.4 on 2024-10-18 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0117_clubapprovalresponsetemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnershipRequest",
            fields=[
                ("id", models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID")),
                ("withdrew", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to="clubs.club")),
                ("person", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("person", "club")},
            },
        ),
        migrations.RenameField(
            model_name="ownershiprequest",
            old_name="withdrew",
            new_name="withdrawn",
        ),
        migrations.RenameField(
            model_name="ownershiprequest",
            old_name="person",
            new_name="requester",
        ),
        migrations.AlterField(
            model_name="ownershiprequest",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="clubs.club"
            ),
        ),
        migrations.AlterField(
            model_name="ownershiprequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RenameField(
            model_name="membershiprequest",
            old_name="withdrew",
            new_name="withdrawn",
        ),
        migrations.RenameField(
            model_name="membershiprequest",
            old_name="person",
            new_name="requester",
        ),
        migrations.AlterField(
            model_name="membershiprequest",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="clubs.club"
            ),
        ),
        migrations.AlterField(
            model_name="membershiprequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
