# Generated by Django 5.0.4 on 2025-01-02 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0117_clubapprovalresponsetemplate"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="ticket_drop_time",),
        migrations.RemoveField(model_name="event", name="ticket_order_limit",),
        migrations.CreateModel(
            name="TicketSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_limit", models.IntegerField(blank=True, null=True)),
                ("drop_time", models.DateTimeField(blank=True, null=True)),
                ("fee_charged_to_buyer", models.BooleanField(default=False)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_settings",
                        to="clubs.event",
                    ),
                ),
            ],
        ),
    ]
