# Generated by Django 5.0.4 on 2025-01-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0117_clubapprovalresponsetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
