# Generated by Django 5.0.4 on 2025-01-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0117_clubapprovalresponsetemplate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="applicationcommittee",
            unique_together={("name", "application")},
            db_constraint=False,  # Don't enforce at DB level yet
        ),
    ]
