# Generated by Django 5.0.4 on 2025-01-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0118_alter_applicationcommittee_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationcommittee",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
