# Generated by Django 5.0.4 on 2025-01-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0118_remove_event_ticket_drop_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsettings",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
