# Generated by Django 5.0.4 on 2024-10-18 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0118_ownershiprequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="ownershiprequest",
            old_name="withdrew",
            new_name="withdrawn",
        ),
        migrations.RenameField(
            model_name="ownershiprequest",
            old_name="person",
            new_name="requester",
        ),
        migrations.AlterField(
            model_name="ownershiprequest",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership_requests",
                to="clubs.club"
            ),
        ),
        migrations.AlterField(
            model_name="ownershiprequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership_requests",
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
