# Generated by Django 5.0.4 on 2025-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0118_remove_event_ticket_drop_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketsettings",
            name="order_limit",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
