# Generated by Django 5.1 on 2025-03-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0119_registrationqueuesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="code_discount",
            field=models.DecimalField(blank=True, decimal_places=2,
                                      default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="ticket",
            name="discount_code_applied",
            field=models.BooleanField(default=False),
        ),
    ]
