# Generated by Django 5.1.7 on 2025-03-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import clubs.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0119_registrationqueuesettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="club",
        ),
        migrations.RemoveField(
            model_name="event",
            name="code",
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image_small",
        ),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="url",
        ),
        migrations.CreateModel(
            name="EventGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True,
                        upload_to=clubs.models.get_event_file_name
                    ),
                ),
                (
                    "image_small",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=clubs.models.get_event_small_file_name,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=2048, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "Recruitment"),
                            (2, "GBM"),
                            (3, "Speaker"),
                            (4, "Activities Fair"),
                            (5, "Social"),
                            (6, "Career"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_groups",
                        to="clubs.club",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="clubs.eventgroup",
            ),
        ),
    ]
