# Generated by Django 5.0.4 on 2025-02-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0119_remove_event_description_remove_event_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="club",
        ),
    ]
