# Generated by Django 5.0.4 on 2025-01-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0119_alter_ticketsettings_order_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsettings",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
