# Generated by Django 5.0.4 on 2025-01-18 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0120_ticketsettings_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettransactionrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tickettransactionrecord",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tickettransactionrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tickettransactionrecord",
            name="buyer_email",
            field=models.EmailField(default="contact@pennclubs.com", max_length=254),
            preserve_default=False,
        ),
    ]
