# Generated by Django 5.1.7 on 2025-04-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0120_event_showing_add_fields_nondestructive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent_recurring_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_drop_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_order_limit',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AlterField(
            model_name='zoommeetingvisit',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clubs.event'),
        ),
        migrations.DeleteModel(
            name='RecurringEvent',
        ),
    ]
