# Generated by Django 5.0.4 on 2025-02-15 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0120_remove_event_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="clubs.eventgroup",
            ),
        ),
    ]
