# Generated by Django 5.0.4 on 2025-03-23 16:54

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0120_ticketsettings_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.IntegerField(
                        choices=[
                            (1, "Free Response"),
                            (2, "Multiple Choice"),
                            (3, "Short Answer"),
                            (4, "Informational Text"),
                        ],
                        default=1,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("precedence", models.IntegerField(default=0)),
                ("word_limit", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("optional", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="clubs.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckoutMultipleChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice",
                        to="clubs.checkoutquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
