# Generated by Django 5.0.4 on 2025-02-28 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0121_alter_event_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.AddField(
            model_name="eventgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="code",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="eventgroup",
            name="code",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
