# Generated by Django 5.1.7 on 2025-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0121_remove_event_parent_recurring_event_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationcommittee',
            unique_together={('application', 'name')},
        ),
    ]
