# Generated by Django 5.1.7 on 2025-04-14 18:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0121_remove_event_parent_recurring_event_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="checkout_context",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="buyable",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="carts",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="group_discount",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="group_size",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="holder",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="holding_expiration",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="showing",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="transferable",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="type",
        ),
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="owner_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tickettransactionrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tickettransactionrecord",
            name="buyer_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "showing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="clubs.eventshowing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("remaining", models.PositiveIntegerField()),
                ("transferable", models.BooleanField(default=True)),
                (
                    "group_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=3
                    ),
                ),
                ("buyable", models.BooleanField(default=True)),
                ("group_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "showing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_classes",
                        to="clubs.eventshowing",
                    ),
                ),
            ],
            options={
                "unique_together": {("showing", "name")},
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clubs.cart",
                    ),
                ),
                (
                    "ticket_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="clubs.ticketclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_class",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="clubs.ticketclass",
            ),
            preserve_default=False,
        ),
    ]
