# Generated by Django 5.1.7 on 2025-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0121_remove_event_parent_recurring_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownershiprequest",
            name="withdrawn",
        ),
        migrations.AddField(
            model_name="ownershiprequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Withdrawn"),
                    (3, "Denied"),
                    (4, "Accepted")
                ],
                default=1
            ),
        ),
    ]
