# Generated by Django 5.1.7 on 2025-04-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0121_remove_event_parent_recurring_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettransactionrecord',
            name='buyer_phone',
        ),
        migrations.RemoveField(
            model_name='tickettransactionrecord',
            name='reconciliation_id',
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
