# Generated by Django 5.2.4 on 2025-07-27 04:50

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_eligibilities(apps, schema_editor):
    """
    Create default categories and eligibilities.
    """
    Category = apps.get_model('clubs', 'Category')
    Eligibility = apps.get_model('clubs', 'Eligibility')
    
    # Create default categories
    categories = [
        "Academic & Pre-Professional",
        "Arts & Performance", 
        "Civic Engagement & Community Service",
        "Cultural & International",
        "Greek Life",
        "Instructional & Competitive (Non Sports-Related)",
        "Media & Publication",
        "Peer Education & Support",
        "Political & Advocacy",
        "Religious & Spiritual",
        "Special Interest",
        "Sports & Recreational",
        "Student Governance",
    ]
    
    for category_name in categories:
        Category.objects.get_or_create(name=category_name)
    
    # Create default eligibility options
    eligibilities = [
        "ALTERNATIVE",
        "GAPSA",
        "SAC",
        "SCHOOL-SPECIFIC",
        "UA",
        "NOT ELIGIBLE",
    ]
    
    for eligibility_name in eligibilities:
        Eligibility.objects.get_or_create(name=eligibility_name)


def reverse_categories_and_eligibilities(apps, schema_editor):
    """
    Reverse the category and eligibility creation.
    """
    Category = apps.get_model('clubs', 'Category')
    Eligibility = apps.get_model('clubs', 'Eligibility')
    Category.objects.all().delete()
    Eligibility.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0122_alter_applicationcommittee_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Eligibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Eligibilities",
            },
        ),
        # Add the category field as nullable
        migrations.AddField(
            model_name="club",
            name="category",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.category",
            ),
        ),
        # Create categories and eligibilities
        migrations.RunPython(
            create_categories_and_eligibilities,
            reverse_categories_and_eligibilities,
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clubs.category",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="eligibility",
            field=models.ManyToManyField(
                blank=True, related_name="clubs", to="clubs.eligibility"
            ),
        ),
    ]
