# Generated by Django 5.0.4 on 2025-03-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0122_remove_event_name_eventgroup_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="code",
        ),
    ]
