# Generated by Django 5.2.4 on 2025-08-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0123_category_eligibility_club_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "verbose_name_plural": "Classifications",
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Designations",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Statuses",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Types",
            },
        ),
        migrations.AlterField(
            model_name="badge",
            name="color",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="historicalclub",
            name="description",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="club",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.classification",
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clubs.classification",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.designation",
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clubs.designation",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="Indicates a clubs's current registration status.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.status",
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Indicates a clubs's current registration status.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clubs.status",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.type",
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clubs.type",
            ),
        ),
    ]
