# Generated by Django 5.2.4 on 2025-08-05 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0123_category_eligibility_club_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_penalty', models.FloatField(default=-1000)),
                ('favorites_per', models.FloatField(default=0.04)),
                ('tags_good', models.FloatField(default=15)),
                ('tags_many', models.FloatField(default=7)),
                ('officer_bonus', models.FloatField(default=15)),
                ('member_base', models.FloatField(default=10)),
                ('member_per', models.FloatField(default=0.1)),
                ('logo_bonus', models.FloatField(default=15)),
                ('subtitle_bad', models.FloatField(default=-10)),
                ('subtitle_good', models.FloatField(default=5)),
                ('images_bonus', models.FloatField(default=3)),
                ('desc_short', models.FloatField(default=25)),
                ('desc_med', models.FloatField(default=10)),
                ('desc_long', models.FloatField(default=10)),
                ('fair_bonus', models.FloatField(default=10)),
                ('application_bonus', models.FloatField(default=25)),
                ('today_event_base', models.FloatField(default=10)),
                ('today_event_good', models.FloatField(default=10)),
                ('week_event_base', models.FloatField(default=5)),
                ('week_event_good', models.FloatField(default=5)),
                ('email_bonus', models.FloatField(default=10)),
                ('social_bonus', models.FloatField(default=10)),
                ('howto_penalty', models.FloatField(default=-30)),
                ('outdated_penalty', models.FloatField(default=-10)),
                ('testimonial_one', models.FloatField(default=10)),
                ('testimonial_three', models.FloatField(default=5)),
                ('random_scale', models.FloatField(default=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ranking_weights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
