# Generated by Django 5.2.4 on 2025-07-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0123_category_eligibility_club_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Badge",
            new_name="Affiliation",
        ),
        migrations.RenameField(
            model_name="club",
            old_name="badges",
            new_name="affiliations",
        ),
    ]
