# Generated by Django 5.0.4 on 2025-03-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0119_registrationqueuesettings"),
        ("clubs", "0123_remove_event_code"),
    ]

    operations = []
