# Generated by Django 5.2.4 on 2025-08-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0124_classification_designation_status_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="historicalclub",
            name="designation",
        ),
        migrations.AddField(
            model_name="category",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                help_text="The SAC funding designation automatically assigned to clubs in this category.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="clubs.designation",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.category",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="clubs.classification",
            ),
        ),
    ]
