# Generated by Django 5.2.4 on 2025-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0124_rankingweights"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_constitution",
            field=models.BooleanField(default=False),
        ),
    ]
