# Generated by Django 5.2.4 on 2025-08-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0124_rankingweights"),
        ("clubs", "0125_remove_club_designation_and_more"),
    ]

    operations = []
