# Generated by Django 5.2.4 on 2025-08-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0126_merge_20250810_2354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="color",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="category",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                help_text="The SAC funding designation automatically assigned to clubs\n        in this category.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="clubs.designation",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="eligibility",
            field=models.ManyToManyField(related_name="clubs", to="clubs.eligibility"),
        ),
    ]
