# Generated by Django 5.2.4 on 2025-08-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0127_alter_badge_color_alter_category_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="group_activity_assessment",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of activities the club engages in",
            ),
        ),
        migrations.AddField(
            model_name="historicalclub",
            name="group_activity_assessment",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of activities the club engages in",
            ),
        ),
    ]
