# Generated by Django 5.2.4 on 2025-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0128_club_group_activity_assessment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupActivityOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this option is currently available for selection",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order for the frontend"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "text"],
            },
        ),
    ]
