# Generated by Django 5.2.4 on 2025-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0129_add_group_activity_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalclub",
            name="group_activity_assessment",
        ),
        migrations.RemoveField(
            model_name="club",
            name="group_activity_assessment",
        ),
        migrations.AddField(
            model_name="club",
            name="group_activity_assessment",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of activities the club engages in",
                to="clubs.groupactivityoption",
            ),
        ),
    ]
