# Generated by Django 5.2.4 on 2025-08-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0130_remove_historicalclub_group_activity_assessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="tags",
            field=models.ManyToManyField(blank=True, to="clubs.tag"),
        ),
    ]
