# Generated by Django 5.2.4 on 2025-10-04 00:24

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0131_alter_club_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationqueuesettings',
            name='new_approval_date_of_next_flip',
            field=models.DateField(default=clubs.models.thirty_days_from_now, help_text='Date when new approval queue will next flip state'),
        ),
        migrations.AddField(
            model_name='registrationqueuesettings',
            name='reapproval_date_of_next_flip',
            field=models.DateField(default=clubs.models.thirty_days_from_now, help_text='Date when reapproval queue will next flip state'),
        ),
    ]
