# Generated by Django 5.2.4 on 2025-10-02 17:07

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0131_alter_club_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmission',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Rejected after written application'), (3, 'Rejected after interview(s)'), (4, 'Accepted')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='badge',
            name='purpose',
            field=models.CharField(choices=[('fair', 'Fair'), ('org', 'Organization')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='application_end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='application_start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='result_release_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clubfair',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clubfair',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ics_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Recruitment'), (2, 'GBM'), (3, 'Speaker'), (4, 'Activities Fair'), (5, 'Social'), (6, 'Career')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='eventshowing',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(0, 'Owner'), (10, 'Officer'), (20, 'Member')], db_index=True, default=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['approved', 'archived'], name='clubs_club_approve_a30dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='clubfair',
            index=models.Index(fields=['end_time', 'start_time'], name='fair_time_idx'),
        ),
        migrations.AddIndex(
            model_name='clubvisit',
            index=models.Index(fields=['club', 'visit_type', 'created_at'], name='clubs_clubv_club_id_3cfb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventshowing',
            index=models.Index(fields=['start_time', 'end_time'], name='clubs_event_start_t_d0f1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventshowing',
            index=models.Index(fields=['event', 'start_time'], name='event_start_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['showing', 'type'], name='clubs_ticke_showing_94ab22_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['showing', 'owner'], name='clubs_ticke_showing_7450aa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['showing', 'holder'], name='clubs_ticke_showing_86d999_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(condition=models.Q(('buyable', True), ('holder__isnull', True), ('owner__isnull', True)), fields=['showing', 'type'], name='ticket_available_idx'),
        ),
    ]
