# Generated by Django 5.2.4 on 2025-10-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0131_alter_club_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationqueuesettings',
            name='new_approval_date_of_next_flip',
            field=models.DateTimeField(help_text='Date when new approval queue will next flip state', null=True),
        ),
        migrations.AddField(
            model_name='registrationqueuesettings',
            name='reapproval_date_of_next_flip',
            field=models.DateTimeField(help_text='Date when reapproval queue will next flip state', null=True),
        ),
    ]
