# Generated by Django 5.2.4 on 2025-10-05 18:09

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0131_alter_club_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationqueuesettings',
            name='new_approval_date_of_next_flip',
            field=models.DateTimeField(default=clubs.models.default_queue_flip_datetime, help_text='Date when new approval queue will next flip state'),
        ),
        migrations.AddField(
            model_name='registrationqueuesettings',
            name='reapproval_date_of_next_flip',
            field=models.DateTimeField(default=clubs.models.default_queue_flip_datetime, help_text='Date when reapproval queue will next flip state'),
        ),
    ]
