# Generated by Django 5.2.4 on 2025-12-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0132_alter_ownershiprequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='visible_to_public',
            field=models.BooleanField(db_index=True, default=False, help_text='If false, hide the club from unauthenticated/non-Penn users.'),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='visible_to_public',
            field=models.BooleanField(db_index=True, default=False, help_text='If false, hide the club from unauthenticated/non-Penn users.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='org',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
