# Generated by Django 5.2.4 on 2025-11-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0132_alter_ownershiprequest_unique_together_and_more'),
        ('clubs', '0132_registrationqueuesettings_new_approval_date_of_next_flip_and_more'),
    ]

    operations = [
    ]
