# Generated by Django 5.2.4 on 2025-11-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0133_merge_20251114_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='org',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
