# Generated by Django 5.2.4 on 2025-12-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0133_club_visible_to_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshowing',
            name='location_visible_to_public',
            field=models.BooleanField(default=False, help_text="If false, hide this showing's location from unauthenticated/non-Penn users."),
        ),
    ]
