# Generated by Django 5.2.4 on 2026-01-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0134_eventshowing_location_visible_to_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='visible_to_public',
            field=models.BooleanField(db_index=True, default=False, help_text='If false, hide the club from unauthenticated users.'),
        ),
        migrations.AlterField(
            model_name='eventshowing',
            name='location_visible_to_public',
            field=models.BooleanField(default=False, help_text="If false, hide this showing's location from unauthenticated users."),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='visible_to_public',
            field=models.BooleanField(db_index=True, default=False, help_text='If false, hide the club from unauthenticated users.'),
        ),
    ]
