# Generated by Django 5.2.4 on 2026-01-25 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0135_alter_club_visible_to_public_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettransactionrecord',
            old_name='reconciliation_id',
            new_name='reference_number',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='checkout_context',
        ),
        migrations.AddField(
            model_name='cart',
            name='pending_transaction_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='decision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='reason_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettransactionrecord',
            name='transaction_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
