# Generated by Django 5.2.4 on 2026-01-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0134_alter_badge_org'),
        ('clubs', '0136_rename_reconciliation_id_tickettransactionrecord_reference_number_and_more'),
    ]

    operations = [
    ]
