# Generated by Django 5.2.4 on 2026-03-01 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0137_merge_20260130_1741"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["person", "role", "club"], name="clubs_membe_person__16cabc_idx"
            ),
        ),
    ]
