# Generated by Django 5.2.4 on 2026-07-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0138_membership_clubs_membe_person__16cabc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='constitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constitution_for_clubs', to='clubs.asset'),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='constitution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clubs.asset'),
        ),
    ]
