# Generated by Django 5.2.4 on 2026-07-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0139_club_constitution_historicalclub_constitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
    ]
