from django.db import migrations


# Programs listed in the Penn course catalog (catalog.upenn.edu/programs) that
# were absent from the Major table. Penn adds programs each year — notably the
# Raj and Neera Singh Program in Artificial Intelligence — but nothing syncs
# this table, so it had drifted well behind the catalog.
#
# Names use the catalog's own "Program, DEGREE" convention, matching the
# existing rows. Entries already present under a different concentration
# convention (e.g. "Africana Studies: African American Studies, BA" vs the
# catalog's "Africana Studies, BA: African American Studies") were deliberately
# excluded, so this migration cannot introduce a duplicate of an existing major.
MISSING_MAJORS = [
    "Adult Oncology Specialty, Certificate",
    "Adult Oncology Specialty, Minor",
    "Advanced Dental Studies, MADS",
    "Advanced Research Training for Genetic Counselors, Certificate",
    "Advanced Scientific Computing, Certificate",
    "Animal Welfare and Behavior, MSAWB",
    "Anthropology, PhD: Biological",
    "Applied Criminology and Police Leadership, MCPL",
    "Applied Economics and Data Science, MEDS",
    "Architecture, BA: Intensive Design",
    "Architecture, MEBD",
    "Architecture, MSD: Property Development and Design",
    "Architecture, MSD: Robotics and Autonomous Systems",
    "Artificial Intelligence for Business, BS",
    "Artificial Intelligence for Business, MBA",
    "Artificial Intelligence, BSE",
    "Artificial Intelligence, Certificate",
    "Artificial Intelligence, MSE",
    "Biochemistry, Biophysics and Chemical Biology, PhD",
    "Biology, BA",
    "Biomedical Informatics, MSBMI",
    "Biostatistics, MS",
    "Chemical & Biomolecular Engineering, Minor",
    "Cinema and Media Studies, MA",
    "Cinema and Media Studies, PhD",
    "City & Regional Planning, MCP",
    "City & Regional Planning, PhD",
    "Climate Science, Certificate",
    "Clinical Informatics, MCI",
    "Communication and Media Industries, MCMI",
    "Communication, BA: Communication, Culture & Journalism Studies",
    "Communication, BA: Data & Network Science for Communication",
    "Communication, BA: Media, Audiences & Persuasion",
    "Communication, BA: Politics, Policy & Advocacy",
    "Computer Science Fundamentals, Certificate",
    "Computer Science, MASCS",
    "Data Analytics in Social Policy, Minor",
    "Data Science and Analytics, Minor",
    "Data Science and Artificial Intelligence, MSE",
    "Data Science, Certificate",
    "Design, Minor",
    "Dialogue, Ethics, and Social Good, Certificate",
    "Digital Storytelling and Content Creation, Certificate",
    "Digital Strategies and Applications, Certificate",
    "ESL Specialist, Certification",
    "Earth and Environmental Science, BA",
    "East Asian Languages and Civilizations, BA: Dual Language",
    "East Asian Languages and Civilizations, BA: General East Asian Languages and Civilizations",
    "Education Studies, MSEd",
    "Energy and Sustainability Engineering, MSE",
    "Engineering Entrepreneurship, Certificate",
    "Engineering Geology, Certificate",
    "Entrepreneurship and Innovation, BS",
    "Environmental Hydrogeology, Certificate",
    "Executive Leadership, DNP",
    "Francophone, Italian and Germanic Studies, BA: Dual Language",
    "Francophone, Italian and Germanic Studies, BA: French and Francophone Studies",
    "Francophone, Italian and Germanic Studies, BA: Germanic Studies",
    "Francophone, Italian and Germanic Studies, BA: Italian Studies",
    "Francophone, Italian and Germanic Studies, PhD: French and Francophone Studies",
    "Francophone, Italian and Germanic Studies, PhD: Germanic Studies",
    "Francophone, Italian and Germanic Studies, PhD: Italian Studies",
    "Gender, Sexuality, & Women's Studies, BA: Feminist Studies",
    "Gender, Sexuality, & Women's Studies, BA: General",
    "Gender, Sexuality, & Women's Studies, BA: Global Gender and Sexuality Studies",
    "Gender, Sexuality, & Women's Studies, BA: Health and Disability Studies",
    "Gender, Sexuality, & Women's Studies, BA: LGBTQ Studies",
    "Gender, Sexuality, & Women's Studies, BA: Self Designed",
    "Global Higher Education Management, MSEd",
    "Global Public Administration, Certificate",
    "Global and Regional Studies, Certificate",
    "Global, MPA",
    "Greek and Latin Languages and Literatures, PhD",
    "Health Care and Technology, Certificate",
    "Health and Societies, BA: Bioethics and Society",
    "Healthcare Quality and Safety, Certificate",
    "Healthcare Quality and Safety, MHQS",
    "Historic Preservation, MSD",
    "History, BA: Political History",
    "Impact, Value and Sustainable Business, BS",
    "Impact, Value and Sustainable Business, MBA",
    "Implementation Science, Certificate",
    "Individualized Studies, BAAS",
    "International Impact Evaluation, MPA",
    "International Studies, BA",
    "International Studies, MA",
    "Italian Studies, Minor",
    "JD/MBA Dual Degree program",
    "Language, Globalization and Intercultural Studies, MSEd",
    "Latin American & Latinx Studies, BA",
    "Latin American and Latinx Studies, Minor",
    "Law and Society, BA",
    "Leading Across Differences, BS",
    "Leading Across Differences, MBA",
    "Learning Analytics and Artificial Intelligence, MSEd",
    "Learning Sciences & Technologies, PhD",
    "Literacy Studies, EdD",
    "Literacy Studies, MSEd",
    "Literacy Studies, PhD",
    "Medical Physics, MSMP",
    "Middle Eastern Languages & Cultures, BA: Ancient Middle East",
    "Middle Eastern Languages & Cultures, BA: Arabic & Hebrew Studies",
    "Middle Eastern Languages & Cultures, BA: Arabic Language and Literature",
    "Middle Eastern Languages & Cultures, BA: Cultures and Societies of the Middle East and North Africa",
    "Middle Eastern Languages & Cultures, BA: Hebrew and Judaic Studies",
    "Middle Eastern Languages & Cultures, BA: Persian Languages & Literature",
    "Middle Eastern Languages & Cultures, MA: Biblical Studies",
    "Middle Eastern Languages & Cultures, MA: Egyptology",
    "Middle Eastern Languages & Cultures, MA: Hebrew and Judaic Studies",
    "Middle Eastern Languages & Cultures, MA: Mesopotamian Civilization",
    "Middle Eastern Languages & Cultures, MA: Middle Eastern Literatures & Societies",
    "Middle Eastern Languages & Cultures, PhD: Biblical Studies",
    "Middle Eastern Languages & Cultures, PhD: Egyptology",
    "Middle Eastern Languages & Cultures, PhD: Hebrew and Judaic Studies",
    "Middle Eastern Languages & Cultures, PhD: Mesopotamian Civilization",
    "Middle Eastern Languages & Cultures, PhD: Middle Eastern Literatures & Societies",
    "Middle Eastern Languages & Cultures: Ancient Middle East, Minor",
    "Middle Eastern Languages & Cultures: Arabic & Hebrew Studies, Minor",
    "Middle Eastern Languages & Cultures: Arabic Language and Literature, Minor",
    "Middle Eastern Languages & Cultures: Cultures and Societies of the Middle East and North Africa, Minor",
    "Middle Eastern Languages & Cultures: Hebrew & Judaic Studies, Minor",
    "Middle Eastern Languages & Cultures: Persian Language & Literature, Minor",
    "Music, Minor",
    "Music, PhD: Composition",
    "Music, PhD: Music Studies",
    "Neuroscience and Health Care Management, Minor",
    "Neuroscience, BA",
    "Neuroscience, Minor",
    "Nonprofit Administration, DNPA",
    "Nursing & Healthcare Leadership, MSN",
    "Nursing, MPN",
    "Nutrition Science, BSN",
    "Nutrition Science, MSNS",
    "Nutrition, Certificate",
    "One Health, Certificate",
    "Oral Biology, MSOB",
    "Oral Health Sciences, MOHS",
    "Oral and Population Health, MSOPH",
    "Pediatric Dentistry, Certificate",
    "Periodontics and Prosthodontics, Certificate",
    "Philosophy, BA: Moral and Political Philosophy",
    "Philosophy, BA: Philosophy of Science",
    "Physical and Life Sciences, BAAS",
    "Pre-Health Core Studies, Post-Baccalaureate Preparatory Program",
    "Pre-Health Specialized Studies, Post-Baccalaureate Preparatory Program",
    "Prosthodontics, Certificate",
    "Quantitative Finance, MBA",
    "Quantitative Finance, MSQF",
    "Quantitative Policy Analysis, MPA",
    "Reading Specialist, Certification",
    "Regulatory Affairs, Certificate",
    "Regulatory Science, MSRS",
    "Russian Language, Literature and Culture, Minor",
    "Russian and East European Studies, BA",
    "Russian and East European Studies, Minor",
    "School Leadership, Certification",
    "Science Foundations, Certificate",
    "Secondary Education, Minor",
    "Social Policy + Data Analytics, MSSP",
    "Social and Governance Factors for Business, MBA",
    "Sociology, BA: Applied Research and Data Analysis",
    "Sociology, BA: Cities, Markets, and the Global Economy",
    "Sociology, BA: Culture and Diversity",
    "Sociology, BA: Education and Society",
    "Sociology, BA: Family, Gender and Society",
    "Sociology, BA: Medical Sociology",
    "Software Systems and Cybersecurity, MSE",
    "Software Systems, Certificate",
    "Spanish and Portuguese, PhD",
    "Statistics and Data Science, BS",
    "Statistics and Data Science, MA",
    "Statistics and Data Science, MBA",
    "Statistics and Data Science, Minor",
    "Statistics and Data Science, PhD",
    "Strategic Climate Communication, Advanced Certificate",
    "Sustainability Design & Engineering, Certificate",
    "Systems Leadership, DNP",
    "Team Culture and Collaboration, Certificate",
    "Technology and Innovation, MSE",
    "UpSkill, Certificate",
    "Urban Education, MSEd",
    "Visual and Interactive Computing, BSE",
    "Writing, BAAS",
    "Yiddish, Minor",
]


def add_missing_majors(apps, schema_editor):
    """
    Purely additive. Existing rows are never renamed or deleted: Major is
    referenced by Profile.major (M2M) and by TargetMajor with on_delete=CASCADE,
    so removing a row would silently strip it from student profiles and delete
    club targeting rules.
    """
    Major = apps.get_model("clubs", "Major")
    existing = set(Major.objects.values_list("name", flat=True))
    Major.objects.bulk_create(
        [Major(name=name) for name in MISSING_MAJORS if name not in existing]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0143_split_club_reject_permission"),
    ]

    operations = [
        # No reverse: deleting these rows would cascade into TargetMajor and
        # detach majors from any profile that had since selected one.
        migrations.RunPython(add_missing_majors, migrations.RunPython.noop),
    ]
