# Generated by Django 2.1.5 on 2019-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20190208_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
