# Generated by Django 2.2.4 on 2019-10-11 17:00

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models

import clubs.models


def create_profiles(apps, schema_editor):
    Profile = apps.get_model('clubs', 'Profile')
    db_alias = schema_editor.connection.alias
    for user in get_user_model().objects.all():
        Profile.using(db_alias).objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('clubs', '0002_auto_20190926_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clubs.models.get_user_file_name)),
            ],
        ),
        migrations.RunPython(
            create_profiles,
            lambda apps, schema_editor: None
        ),
    ]
