# Generated by Django 2.1.5 on 2019-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.ManyToManyField(to='clubs.Tag'),
        ),
    ]
