# Generated by Django 2.1.7 on 2019-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20190217_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AddField(
            model_name='club',
            name='accepting_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='application_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='club',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
