# Generated by Django 2.2.5 on 2019-11-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_merge_20191025_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='parent_orgs',
            field=models.ManyToManyField(blank=True, related_name='children_orgs', to='clubs.Club'),
        ),
    ]
