# Generated by Django 2.2.6 on 2019-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_profile'),
        ('clubs', '0004_merge_20191025_2143'),
    ]

    operations = [
    ]
