# Generated by Django 2.1.7 on 2019-03-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20190322_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='size',
            field=models.IntegerField(choices=[(1, '1-20'), (2, '21-50'), (3, '51-100'), (4, '101+')], default=1),
        ),
    ]
