# Generated by Django 2.2.3 on 2019-07-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20190324_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='accepting_applications',
            new_name='application_available',
        ),
        migrations.RemoveField(
            model_name='club',
            name='fact',
        ),
        migrations.AddField(
            model_name='club',
            name='how_to_get_involved',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='listserv_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
