# Generated by Django 2.2.6 on 2019-11-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20191103_1843'),
        ('clubs', '0005_auto_20191103_1810'),
    ]

    operations = [
    ]
