# Generated by Django 2.2.4 on 2019-08-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20190728_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Member', max_length=255)),
                ('role', models.IntegerField(choices=[(0, 'Owner'), (10, 'Officer'), (20, 'Member')], default=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
        ),
    ]
