# Generated by Django 2.2.4 on 2019-08-25 16:14
# Modified by ezwang on 2019-08-25 to add custom image migration

import os

import django.db.models.deletion
import requests
from django.conf import settings
from django.core.files.base import ContentFile
from django.db import migrations, models

import clubs.models


def move_images(apps, schema_editor):
    """
    Convert image URLs to image fields by downloading and saving the image.
    """
    Club = apps.get_model('clubs', 'Club')
    for club in Club.objects.all():
        url = club.image_url
        if url:
            resp = requests.get(url, allow_redirects=True)
            resp.raise_for_status()
            club.image.save(os.path.basename(url), ContentFile(resp.content))
            club.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0008_auto_20190821_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.get_club_file_name),
        ),
        migrations.RunPython(
            move_images,
            lambda apps, schema_editor: None
        ),
        migrations.RemoveField(
            model_name='club',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.get_event_file_name),
        ),
        migrations.AddField(
            model_name='membership',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipinvite',
            name='role',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='membershipinvite',
            name='title',
            field=models.CharField(default='Member', max_length=255),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=clubs.models.get_asset_file_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
