# Generated by Django 2.2.6 on 2019-11-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_merge_20191108_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='club',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
            preserve_default=False,
        ),
    ]
