# Generated by Django 2.2.4 on 2019-08-25 16:14

import clubs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0008_auto_20190821_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.get_club_file_name),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.get_event_file_name),
        ),
        migrations.AddField(
            model_name='membership',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipinvite',
            name='role',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='membershipinvite',
            name='title',
            field=models.CharField(default='Member', max_length=255),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=clubs.models.get_asset_file_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
