# Generated by Django 2.2.6 on 2019-11-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20191111_1835'),
        ('clubs', '0008_subscribe'),
    ]

    operations = [
    ]
