# Generated by Django 2.2.6 on 2019-11-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_merge_20191108_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
