# Generated by Django 2.2.6 on 2019-11-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20191110_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='club',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
