# Generated by Django 2.2.4 on 2019-08-25 22:05

from django.db import migrations, models
import django.db.models.deletion


def copy_field(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    for club in Club.objects.all():
        club.code = club.id
        club.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20190825_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_field,
            lambda apps, schema_editor: None
        ),
        migrations.AlterField(
            model_name='favorite',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', to_field='code'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', to_field='code'),
        ),
        migrations.AlterField(
            model_name='membershipinvite',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', to_field='code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', to_field='code'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='club',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='membershipinvite',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
    ]
