# Generated by Django 2.2.6 on 2019-11-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20191110_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
