# Generated by Django 2.2.6 on 2019-11-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20191108_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creating_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_by_club', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_of_club', to='clubs.Club'),
        ),
    ]
