# Generated by Django 2.2.4 on 2019-08-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20190821_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinvite',
            name='role',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='membershipinvite',
            name='title',
            field=models.CharField(default='Member', max_length=255),
        ),
    ]
