# Generated by Django 2.2.4 on 2019-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20190827_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinvite',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
