# Generated by Django 2.2.4 on 2019-08-29 01:23
# Modified by Armaan Tobaccowalla on 2019-08-29

from django.db import migrations, models


def change_application_required(apps, schema_editor):
    """
    Set each application_required field to required by default
    """
    Club = apps.get_model('clubs', 'Club')
    for club in Club.objects.all():
        club.application_required = 3
        club.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_membershipinvite_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='application_available',
            new_name='accepting_members',
        ),
        migrations.RemoveField(
            model_name='club',
            name='listserv_available',
        ),
        migrations.AddField(
            model_name='club',
            name='listserv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='application_required',
            field=models.IntegerField(choices=[(1, 'No Application Required'), (2, 'Application Required For Some Positions'), (3, 'Application Required For All Positions')], default=3),
        ),
        migrations.RunPython(
            change_application_required,
            lambda apps, schema_editor: None
        ),
    ]
