# Generated by Django 2.2.6 on 2019-11-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20191110_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
    ]
