# Generated by Django 2.2.6 on 2019-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20191108_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_tags',
            field=models.ManyToManyField(related_name='tag_of_note', to='clubs.NoteTag'),
        ),
    ]
