# Generated by Django 2.2.4 on 2019-08-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_membership_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
    ]
