# Generated by Django 2.2.4 on 2019-09-01 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20190829_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
