# Generated by Django 2.2.4 on 2019-09-01 21:14

from django.db import migrations, models


def mark_approved(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    Club.objects.all().update(approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20190901_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_approved,
            lambda apps, schema_editor: None,
        ),
    ]
